-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alergias
(
    id bigint NOT NULL DEFAULT nextval('alergias_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    tipo_alergia character varying(100) COLLATE pg_catalog."default",
    descripcion character varying(1000) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT alergias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.antecedentes
(
    id bigint NOT NULL DEFAULT nextval('antecedentes_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    tipo_antecedente character varying(50) COLLATE pg_catalog."default",
    descripcion_antecedente character varying(1000) COLLATE pg_catalog."default",
    fecha_antecedente date,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT antecedentes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.atecedentes_familiares
(
    id bigint NOT NULL DEFAULT nextval('atecedentes_familiares_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    tipo_antecedente character varying(50) COLLATE pg_catalog."default",
    parentesco character varying(100) COLLATE pg_catalog."default",
    descripcion_antecedente character varying(1000) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT atecedentes_familiares_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bathroomhairdresser
(
    id bigint NOT NULL DEFAULT nextval('bathroomhairdresser_id_seq'::regclass),
    fullname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idtype character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idnumber character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_veterinarian character varying(20) COLLATE pg_catalog."default",
    occupation character varying(20) COLLATE pg_catalog."default",
    phone character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city_id bigint NOT NULL,
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    calendy character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bathroomhairdresser_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clinics_services
(
    id integer NOT NULL DEFAULT nextval('clinics_services_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT clinics_services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clinics_services_breakdown
(
    id integer NOT NULL DEFAULT nextval('clinics_services_breakdown_id_seq'::regclass),
    clinic_service_id integer,
    veterinary_clinic_id integer,
    status boolean NOT NULL,
    CONSTRAINT clinics_services_breakdown_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.codes
(
    id bigint NOT NULL DEFAULT nextval('codes_id_seq'::regclass),
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    hashcode character varying(100) COLLATE pg_catalog."default" NOT NULL,
    license character varying(50) COLLATE pg_catalog."default" NOT NULL,
    agreement character varying(50) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'inactive'::character varying,
    CONSTRAINT codes_pkey PRIMARY KEY (id),
    CONSTRAINT codes_code_key UNIQUE (code),
    CONSTRAINT codes_hashcode_key UNIQUE (hashcode)
);

CREATE TABLE IF NOT EXISTS public.condicion
(
    id bigint NOT NULL DEFAULT nextval('condicion_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    discapacidad character varying(100) COLLATE pg_catalog."default",
    embarazada character varying(10) COLLATE pg_catalog."default",
    cicatrices_descripcion character varying(1000) COLLATE pg_catalog."default",
    tatuajes_descripcion character varying(1000) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT condicion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contactos
(
    id bigint NOT NULL DEFAULT nextval('contactos_id_seq'::regclass),
    id_usuario bigint NOT NULL,
    nombre1 character varying(100) COLLATE pg_catalog."default",
    telefono1 character varying(50) COLLATE pg_catalog."default",
    nombre2 character varying(100) COLLATE pg_catalog."default",
    telefono2 character varying(50) COLLATE pg_catalog."default",
    nombre3 character varying(100) COLLATE pg_catalog."default",
    telefono3 character varying(50) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT contactos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dbbomberos
(
    id bigint NOT NULL DEFAULT nextval('dbbomberos_id_seq'::regclass),
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(100) COLLATE pg_catalog."default" NOT NULL,
    registro_bomberos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dbbomberos_pkey PRIMARY KEY (id),
    CONSTRAINT dbbomberos_apellidos_key UNIQUE (apellidos),
    CONSTRAINT dbbomberos_cedula_key UNIQUE (cedula),
    CONSTRAINT dbbomberos_nombres_key UNIQUE (nombres),
    CONSTRAINT dbbomberos_registro_bomberos_key UNIQUE (registro_bomberos)
);

CREATE TABLE IF NOT EXISTS public.dbdefensacivil
(
    id bigint NOT NULL DEFAULT nextval('dbdefensacivil_id_seq'::regclass),
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(100) COLLATE pg_catalog."default" NOT NULL,
    registro_defensa_civil character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dbdefensacivil_pkey PRIMARY KEY (id),
    CONSTRAINT dbdefensacivil_apellidos_key UNIQUE (apellidos),
    CONSTRAINT dbdefensacivil_cedula_key UNIQUE (cedula),
    CONSTRAINT dbdefensacivil_nombres_key UNIQUE (nombres),
    CONSTRAINT dbdefensacivil_registro_defensa_civil_key UNIQUE (registro_defensa_civil)
);

CREATE TABLE IF NOT EXISTS public.dbmedicina
(
    id bigint NOT NULL DEFAULT nextval('dbmedicina_id_seq'::regclass),
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(100) COLLATE pg_catalog."default" NOT NULL,
    registro_medico character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dbmedicina_pkey PRIMARY KEY (id),
    CONSTRAINT dbmedicina_apellidos_key UNIQUE (apellidos),
    CONSTRAINT dbmedicina_cedula_key UNIQUE (cedula),
    CONSTRAINT dbmedicina_nombres_key UNIQUE (nombres),
    CONSTRAINT dbmedicina_registro_medico_key UNIQUE (registro_medico)
);

CREATE TABLE IF NOT EXISTS public.dbpolicia
(
    id bigint NOT NULL DEFAULT nextval('dbpolicia_id_seq'::regclass),
    nombres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(100) COLLATE pg_catalog."default" NOT NULL,
    placa character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dbpolicia_pkey PRIMARY KEY (id),
    CONSTRAINT dbpolicia_apellidos_key UNIQUE (apellidos),
    CONSTRAINT dbpolicia_cedula_key UNIQUE (cedula),
    CONSTRAINT dbpolicia_nombres_key UNIQUE (nombres),
    CONSTRAINT dbpolicia_placa_key UNIQUE (placa)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    id bigint NOT NULL DEFAULT nextval('departments_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code integer NOT NULL,
    CONSTRAINT departments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.documents
(
    id integer NOT NULL DEFAULT nextval('documents_id_seq'::regclass),
    provider_id integer NOT NULL,
    pub_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    priv_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    file_bs64 text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT documents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enfermedades
(
    id bigint NOT NULL DEFAULT nextval('enfermedades_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    enfermedad character varying(200) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT enfermedades_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.establishment
(
    id integer NOT NULL DEFAULT nextval('establishment_id_seq'::regclass),
    provider_id integer NOT NULL,
    own boolean NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT establishment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.hotelnursery
(
    id bigint NOT NULL DEFAULT nextval('hotelnursery_id_seq'::regclass),
    fullname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idtype character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idnumber character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_veterinarian character varying(20) COLLATE pg_catalog."default",
    occupation character varying(20) COLLATE pg_catalog."default",
    phone character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city_id bigint NOT NULL,
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    calendy character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT hotelnursery_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ingreso_salud
(
    id bigint NOT NULL DEFAULT nextval('ingreso_salud_id_seq'::regclass),
    nombres character varying(80) COLLATE pg_catalog."default" NOT NULL,
    numeroid character varying(80) COLLATE pg_catalog."default" NOT NULL,
    hora_ingreso timestamp(0) without time zone NOT NULL,
    CONSTRAINT ingreso_salud_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.legal_representative
(
    id integer NOT NULL DEFAULT nextval('legal_representative_id_seq'::regclass),
    provider_id integer NOT NULL,
    identification_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    identification_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT legal_representative_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.license
(
    id bigint NOT NULL DEFAULT nextval('license_id_seq'::regclass),
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    agreement character varying(50) COLLATE pg_catalog."default" NOT NULL,
    discount numeric(10, 0) NOT NULL,
    price integer NOT NULL,
    total numeric(100, 0) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT license_pkey PRIMARY KEY (id),
    CONSTRAINT license_agreement_key UNIQUE (agreement),
    CONSTRAINT license_code_key UNIQUE (code),
    CONSTRAINT license_discount_key UNIQUE (discount),
    CONSTRAINT license_price_key UNIQUE (price),
    CONSTRAINT license_total_key UNIQUE (total)
);

CREATE TABLE IF NOT EXISTS public.mascotas
(
    id bigint NOT NULL DEFAULT nextval('mascotas_id_seq'::regclass),
    id_usuario bigint NOT NULL,
    hashcode character varying(80) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    especie character varying(50) COLLATE pg_catalog."default" NOT NULL,
    raza character varying(50) COLLATE pg_catalog."default" NOT NULL,
    peso character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sexo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    color character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fechanacimiento date NOT NULL,
    descripcion character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    seguro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    estatura character varying(50) COLLATE pg_catalog."default" NOT NULL,
    temperamento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nochip character varying(100) COLLATE pg_catalog."default",
    photourl character varying(100) COLLATE pg_catalog."default",
    photoname character varying(500) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    petid character varying(50) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    castrated boolean,
    CONSTRAINT mascotas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medicamentos
(
    id bigint NOT NULL DEFAULT nextval('medicamentos_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    medicamento character varying(100) COLLATE pg_catalog."default",
    laboratorio character varying(100) COLLATE pg_catalog."default",
    formula character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT medicamentos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pacientes
(
    id bigint NOT NULL DEFAULT nextval('pacientes_id_seq'::regclass),
    code character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipoid character varying(80) COLLATE pg_catalog."default" NOT NULL,
    numeroid character varying(80) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(30) COLLATE pg_catalog."default" NOT NULL,
    fecha_nacimiento date,
    genero character varying(30) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(50) COLLATE pg_catalog."default" NOT NULL,
    departamento character varying(50) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rh character varying(35) COLLATE pg_catalog."default" NOT NULL,
    eps character varying(50) COLLATE pg_catalog."default",
    prepagada character varying(50) COLLATE pg_catalog."default",
    arl character varying(50) COLLATE pg_catalog."default",
    seguro_funerario character varying(50) COLLATE pg_catalog."default",
    a_cargo_id bigint NOT NULL,
    image character varying(255) COLLATE pg_catalog."default",
    enterprise character varying(255) COLLATE pg_catalog."default",
    nit character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    photourl character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT pacientes_pkey PRIMARY KEY (id),
    CONSTRAINT pacientes_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.personal_salud
(
    id bigint NOT NULL DEFAULT nextval('personal_salud_id_seq'::regclass),
    tipoid character varying(80) COLLATE pg_catalog."default" NOT NULL,
    numeroid character varying(80) COLLATE pg_catalog."default" NOT NULL,
    primer_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    primer_apellido character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT personal_salud_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pertenencias
(
    id bigint NOT NULL DEFAULT nextval('pertenencias_id_seq'::regclass),
    id_user bigint NOT NULL,
    hashcode character varying(80) COLLATE pg_catalog."default" NOT NULL,
    objeto character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(1000) COLLATE pg_catalog."default",
    created_at timestamp(0) without time zone,
    CONSTRAINT pertenencias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.petsdiseasecondition
(
    id bigint NOT NULL DEFAULT nextval('petsdiseasecondition_id_seq'::regclass),
    pet_id bigint NOT NULL,
    typediseasecondition character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    diagnosticdate date NOT NULL,
    status character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT petsdiseasecondition_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.petstreatment
(
    id bigint NOT NULL DEFAULT nextval('petstreatment_id_seq'::regclass),
    pet_id bigint NOT NULL,
    typetreatment character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    status character varying(100) COLLATE pg_catalog."default" NOT NULL,
    startdate date NOT NULL,
    enddate date NOT NULL,
    frequency character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT petstreatment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.petsvaccine
(
    id bigint NOT NULL DEFAULT nextval('petsvaccine_id_seq'::regclass),
    pet_id bigint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    laboratory character varying(100) COLLATE pg_catalog."default" NOT NULL,
    startdate date NOT NULL,
    nextdate date,
    dose character varying(50) COLLATE pg_catalog."default" NOT NULL,
    photourl character varying(10000000) COLLATE pg_catalog."default",
    photoname character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT petsvaccine_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.petsveterinarian
(
    id bigint NOT NULL DEFAULT nextval('petsveterinarian_id_seq'::regclass),
    pet_id bigint NOT NULL,
    fullname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idtype character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idnumber character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city_id bigint NOT NULL,
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    calendy character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT petsveterinarian_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provider
(
    id integer NOT NULL DEFAULT nextval('provider_id_seq'::regclass),
    provider_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    identification_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    identification_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city bigint NOT NULL,
    department character varying(255) COLLATE pg_catalog."default",
    photo_bs64 text COLLATE pg_catalog."default",
    pub_photo character varying(255) COLLATE pg_catalog."default",
    priv_photo character varying(255) COLLATE pg_catalog."default",
    status boolean NOT NULL,
    CONSTRAINT provider_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provider_services
(
    id integer NOT NULL DEFAULT nextval('provider_services_id_seq'::regclass),
    provider_id integer NOT NULL,
    service_id integer NOT NULL,
    status boolean NOT NULL,
    CONSTRAINT provider_services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.services
(
    id integer NOT NULL DEFAULT nextval('services_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.townships
(
    id bigint NOT NULL DEFAULT nextval('townships_id_seq'::regclass),
    department_id bigint NOT NULL,
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT townships_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    code character varying(100) COLLATE pg_catalog."default",
    hashcode character varying(200) COLLATE pg_catalog."default",
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    typeperson character varying(100) COLLATE pg_catalog."default",
    typeid character varying(100) COLLATE pg_catalog."default" NOT NULL,
    numberid character varying(80) COLLATE pg_catalog."default",
    address character varying(100) COLLATE pg_catalog."default",
    city_id bigint,
    phone character varying(80) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    parentesco character varying(100) COLLATE pg_catalog."default",
    notificationid character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    session_token character varying(255) COLLATE pg_catalog."default",
    verificado boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    service character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_code_key UNIQUE (code),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_hashcode_key UNIQUE (hashcode),
    CONSTRAINT users_notificationid_key UNIQUE (notificationid)
);

CREATE TABLE IF NOT EXISTS public.vacunas
(
    id bigint NOT NULL DEFAULT nextval('vacunas_id_seq'::regclass),
    id_paciente bigint NOT NULL,
    vacuna character varying(100) COLLATE pg_catalog."default",
    updated_at timestamp(0) without time zone NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT vacunas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.veterinarians
(
    id bigint NOT NULL DEFAULT nextval('veterinarians_id_seq'::regclass),
    fullname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idtype character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idnumber character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city_id bigint NOT NULL,
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    calendy character varying(100) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    price character varying(10) COLLATE pg_catalog."default",
    reg_veterinarian character varying(20) COLLATE pg_catalog."default",
    occupation character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT veterinarians_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.veterinary_clinics
(
    id integer NOT NULL DEFAULT nextval('veterinary_clinics_id_seq'::regclass),
    business_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    priority character varying(100) COLLATE pg_catalog."default",
    strategy character varying(255) COLLATE pg_catalog."default",
    name_1 character varying(100) COLLATE pg_catalog."default",
    name_2 character varying(100) COLLATE pg_catalog."default",
    last_name_1 character varying(100) COLLATE pg_catalog."default",
    last_name_2 character varying(100) COLLATE pg_catalog."default",
    registration_date date,
    renewal_date date,
    vicinity character varying(255) COLLATE pg_catalog."default",
    township integer,
    phone_1 character varying(15) COLLATE pg_catalog."default",
    phone_2 character varying(15) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    ciiu_1 character varying(500) COLLATE pg_catalog."default",
    ciiu_2 character varying(500) COLLATE pg_catalog."default",
    ciiu_3 character varying(500) COLLATE pg_catalog."default",
    ciiu_4 character varying(500) COLLATE pg_catalog."default",
    activity character varying(500) COLLATE pg_catalog."default",
    company_size character varying(500) COLLATE pg_catalog."default",
    owner_name character varying(500) COLLATE pg_catalog."default",
    legal_representative_name character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT veterinary_clinics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.wellnessspa
(
    id bigint NOT NULL DEFAULT nextval('wellnessspa_id_seq'::regclass),
    fullname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idtype character varying(100) COLLATE pg_catalog."default" NOT NULL,
    idnumber character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_veterinarian character varying(20) COLLATE pg_catalog."default",
    occupation character varying(20) COLLATE pg_catalog."default",
    phone character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city_id bigint NOT NULL,
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    calendy character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT wellnessspa_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.alergias
    ADD CONSTRAINT alergias_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.antecedentes
    ADD CONSTRAINT antecedentes_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.atecedentes_familiares
    ADD CONSTRAINT atecedentes_familiares_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bathroomhairdresser
    ADD CONSTRAINT bathroomhairdresser_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.clinics_services_breakdown
    ADD CONSTRAINT clinics_services_breakdown_clinic_service_id_fkey FOREIGN KEY (clinic_service_id)
    REFERENCES public.clinics_services (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clinics_services_breakdown
    ADD CONSTRAINT clinics_services_breakdown_veterinary_clinic_id_fkey FOREIGN KEY (veterinary_clinic_id)
    REFERENCES public.veterinary_clinics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.condicion
    ADD CONSTRAINT condicion_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.contactos
    ADD CONSTRAINT contactos_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.documents
    ADD CONSTRAINT documents_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.provider (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enfermedades
    ADD CONSTRAINT enfermedades_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.establishment
    ADD CONSTRAINT establishment_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.provider (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.hotelnursery
    ADD CONSTRAINT hotelnursery_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.legal_representative
    ADD CONSTRAINT legal_representative_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.provider (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.mascotas
    ADD CONSTRAINT mascotas_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.medicamentos
    ADD CONSTRAINT medicamentos_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT pacientes_a_cargo_id_fkey FOREIGN KEY (a_cargo_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pertenencias
    ADD CONSTRAINT pertenencias_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.petsdiseasecondition
    ADD CONSTRAINT petsdiseasecondition_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.mascotas (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.petstreatment
    ADD CONSTRAINT petstreatment_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.mascotas (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.petsvaccine
    ADD CONSTRAINT petsvaccine_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.mascotas (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.petsveterinarian
    ADD CONSTRAINT petsveterinarian_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.petsveterinarian
    ADD CONSTRAINT petsveterinarian_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.mascotas (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provider
    ADD CONSTRAINT provider_city_fkey FOREIGN KEY (city)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provider_services
    ADD CONSTRAINT provider_services_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.provider (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provider_services
    ADD CONSTRAINT provider_services_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.services (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.townships
    ADD CONSTRAINT townships_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES public.departments (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_code_fkey FOREIGN KEY (code)
    REFERENCES public.codes (code) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_code_key
    ON public.users(code);


ALTER TABLE IF EXISTS public.vacunas
    ADD CONSTRAINT vacunas_id_paciente_fkey FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.veterinarians
    ADD CONSTRAINT veterinarians_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.veterinary_clinics
    ADD CONSTRAINT veterinary_clinics_township_fkey FOREIGN KEY (township)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wellnessspa
    ADD CONSTRAINT wellnessspa_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.townships (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;